//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SlideKit
import SwiftUI

@MainActor
struct SlideConfiguration {

  /// Edit the slide size.
  let size = SlideSize.standard16_9

  ///  Add your slides into the trailing closure.
  let slideIndexController = SlideIndexController {
    CoverSlide()
    YutailangSlide()
    IntroductionExpressionSoundSlide()

    AboutTitleSlide()
    AboutSlide()

    ExampleExpressionTitleSlide()
    ExampleExpressionSlide()
    ExampleExpressionSoundSlide()

    ImplementationTitleSlide()
    ImplementationSlide()

    SourceNodeTitleSlide()
    SourceNodeSlide()
    ResamplingSlide()

    EvaluatorTitleSlide()
    JavaScriptCoreSlide()
    SwiftEvaluatorSlide()

    ExchangeTitleSlide()
    ExchangeSlide()

    ConclusionTitleSlide()
    ConclusionSlide()
  }
}
